apiVersion: v1
kind: Service
metadata:
  name: {{ include "td4a.fullname" . }}-schema
  labels:
  {{- include "td4a.labels" . | nindent 4 }}
spec:
  type: {{ .Values.schema.type }}
  selector:
    app: td4a-schema
  {{- include "td4a.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.schema.ports | toYaml | nindent 2 -}}